### ISSUE TITLE
Ability to set Namespace when switching contexts

### ISSUE THREAD

**Issue by jwhitcraft** [ahmetb/kubectx#1]
When switching a context, it would be nice to be able to set the active (default) namespace for the context as well.

```sh
kubectx my-cluster test-namespace
```

If test-namespace is left off, it would just be ignored.

**Comment by ahmetb** [comment]
@jwhitcraft Interesting idea. I don’t have a lot of daily experience with namespaces. It looks like if you want to associate a namespace with a context entry, you need to create a new context entry (or modify the existing context entry). 

Please correct me if I'm wrong, but in your example, `my-cluster` would always be associated with the `test-namespace`. I can think of refactoring the kubectx alias functionality to accept a namespace argument like this:

    kubectx c1=my-cluster
    kubectx c2=my-cluster:test-namespace

because there's no way to do `kubectl config use-namespace` today. What do you think of this?

**Comment by jwhitcraft** [comment]
@ahmetb, that works for me.  Currently I do this in my bash script which allows me to keep the same context but change the active namespace at will.

```sh
function k8sns() {
    ctx=`kubectl config current-context`
    ns=$1

    // verify that the namespace exists
    ns=`kubectl get namespace $1 --no-headers --output=go-template={{.metadata.name}} 2>/dev/null`

    if [ -z "${ns}" ]; then
        echo "Namespace (${1}) not found, using default"
        ns="default"
    fi

    kubectl config set-context ${ctx} --namespace="${ns}"
}
```

**Comment by ahmetb** [comment]
@jwhitcraft I see, that's essentially modifying your context. But it should be fine. I have an alternative proposal:

We can ship an additional `kubens` script, just like `kubectx` it can list/auto-complete the namespaces active in the current context and modify the current context to use the namespace, like your script does. It would also provide switching back and forth between namespaces using `kubens –`.

Which solution do you like better, a separate tool, or aliasing feature charged with namespaces?

**Comment by jwhitcraft** [comment]
@ahmetb a seperate tool would be best the more and more i think about it.

**Comment by ahmetb** [comment]
@jwhitcraft I just hacked a `kubens` tool. Can you try check out this branch, add it to your PATH and try `kubens`? https://github.com/ahmetb/kubectx/tree/wip-kubens  I appreciate feedback.

**Comment by jwhitcraft** [comment]
@ahmetb I just got back to work and i'll get this setup today.

Thanks!

**Comment by jwhitcraft** [comment]
@ahmetb, so far working well. nice job 👍

**Comment by ahmetb** [comment]
This can now be installed via `brew install kubectx --HEAD`
