### ISSUE TITLE
kubectx prints context name on a weird black background

### ISSUE THREAD

**Issue by a1ph** [ahmetb/kubectx#191]
I'm using black on white terminal color scheme. kubectx should not change background color for its output.

**Comment by ahmetb** [comment]
So here's the thing:

We want to show "current context" differently. We use "yellow font" to do that. As you might imagine, yellow isn't legible on white backgrounds. So we throw a "black background" on that.

Now the problem is, white terminal schemes see a weird black box for current context, but the dark background folks are just happy (and they're the majority after all).

If you have any proposals to solve this problem, I'm all ears.

**Comment by unixorn** [comment]
Maybe add a check for a `$KUBECTX_BACKGROUND_COLOR` with a default of black? And a `$KUBECTX_CONTEXT_COLOR` with a default of the current yellow so that they can both be customized?

I say that as one of the dark terminal majority, but I can see why people might want to customize. I have my AWS account in my prompt and that segment is white on red when it's production.

**Comment by ahmetb** [comment]
Unless I am mistaken they’re both already customizable. See readme.

**Comment by unixorn** [comment]
You're right @ahmetb, I should have looked there first. I think this can be closed then, there's already functionality in place to solve the issue with a couple `export` commands in `.bashrc`/`.zshrc`.
