### ISSUE TITLE
How to add multiple configs in kubectx

### ISSUE THREAD

**Issue by uhlhosting** [ahmetb/kubectx#201]
I have multiple clusters in ~/.kube/cluster1/config ~/.kube/cluster2/config how can I make kubectx use them? it seems to detect only one config in ~/.kube . Using macos here.

**Comment by ahmetb** [comment]
https://ahmet.im/blog/mastering-kubeconfig/

**Comment by paulseghers** [comment]
The provided fix does not concern kubectx

**Comment by b01** [comment]
:-( `kubectl` supports multiple files, but then `kubectx` does not?

**Comment by ahmetb** [comment]
If you're using bash version of kubectx/kubens, you're using kubectl directly, so it works with multiple files just fine.

The new Go implementation of kubectx/kubectx  is not able to handle this today (as it does not shell out to kubectl) and we need to find what's the right place/way to write back to multiple files and implement the logic that works for most everyone.

The answer isn't as simple as another env var, mostly because there are other actors like auth plugins that write back to kubeconfig files as the kubectl command executes, and those changes are written to the original files, not the merged ones.

**Comment by b01** [comment]
I'm on Windows and I prefer using Powershell. In order to use the bash version I'd have to switch to using WSL all the time or maybe MinGW.
