### ISSUE TITLE
kubens should be switching to other namespace when current namespace is deleted

### ISSUE THREAD

**Issue by srihas619** [ahmetb/kubectx#30]
**current**:

```
$ kubens
default
kube-public
kube-system
management-ui

$ kubectl delete ns management-ui 
namespace "management-ui" deleted

$ kubens
default
kube-public
kube-system
management-ui

$ kubectl get ns
NAME          STATUS    AGE
default       Active    4d
kube-public   Active    4d
kube-system   Active    4d
```
**Expected**:
`management-ui` namespace should not be listed after it has been deleted.

**Comment by ahmetb** [comment]
@srihas619 I think the colors didn't copy here, so I can't tell what `kubens` output exactly was.

If `kubens` command is returning a deleted namespace, it's probably because it's actually not deleted in the k8s APIserver. We're not caching the results, and just calling `kubectl get ns`.

If you create a namespace and delete it, `kubectl get ns` will show it briefly for a while:

```
NAME          STATUS        AGE
default       Active        48d
foo           Terminating   50s <--- this
kube-public   Active        48d
kube-system   Active        48d
```

**Comment by ahmetb** [comment]
I may think of improving this by filtering the `kubectl get ns` with a filter that looks at Status=Active.

**Comment by srihas619** [comment]
Ok, I understood it now, thank you!

**Comment by srihas619** [comment]
ok, I understood now the reason. Thank you!

**Comment by srihas619** [comment]
Ok, I understood the reason, Thank you.
