### ISSUE TITLE
Interactive menu for delete contexts.

### ISSUE THREAD

**Issue by yankeexe** [ahmetb/kubectx#303]
It would be handy to have an interactive menu like the default `kubectx` root command to choose contexts for the delete command as well `kubectx -d`. 
Maybe an additional flag of `-i` for interactive mode. So `kubectx -di` would let the user choose the context entry with an interactive menu for deletion.

![image](https://user-images.githubusercontent.com/13623913/124049733-d61a3e80-da38-11eb-921f-de071b78ef0a.png)

If this looks like an intuitive addition, I would be happy to open a Pull Request.

**Comment by ahmetb** [comment]
@yankeexe Not a bad idea. The only downside I can think of is _accidental deletion_ because you're no longer typing the context name. But we have that problem with the tab-completion in the shell as well.

I am open to it, it's worth implementing only in the go implementation. No need for `-i`. fzf just works when installed.

**Comment by droctothorpe** [comment]
I was literally just about to post this exact issue, heh. Would be happy to PR it as well unless you want dibs on it @yankeexe.

**Comment by yankeexe** [comment]
> I was literally just about to post this exact issue, heh. Would be happy to PR it as well unless you want dibs on it @yankeexe. 

@droctothorpe working on it 🙂
