### ISSUE TITLE
Are go versions still considered not stable?

### ISSUE THREAD

**Issue by adalsa91** [ahmetb/kubectx#383]
I know the README says bash versions are the stable ones and the go versions are the future of this project, but this statement was made on Nov 2021 and as far I can see the last release was v0.9.4 on Jul 2021. I'm not sure which version to use, I mean if it can help to the project I prefer to use go version and be a tester but if the development of the project has stopped I prefer to stay on bash stable versions. Can anyone enlighten me?

In any case, thank you very much for making this tools ❤️

**Comment by ahmetb** [comment]
It works for most cases, but there are some issues with certain cloud providers like Azure that rely on modifying the file and expecting it to be saved back, but since we read the file into memory and use our own yaml manipulation, we don't persist the changes made to the client-go's in-memory copy of kubeconfig file. That's probably the main blocker. But I intend to spend some time on this soon.

**Comment by adalsa91** [comment]
I'm not working with Azure at the moment, so I'm gonna give it a try. Happy to see that you intend to continue improving the tool! Thank you for the answer!
