### ISSUE TITLE
KUBECTX_IGNORE_FZF not being respected

### ISSUE THREAD

**Issue by edclement** [ahmetb/kubectx#91]
> If you have `fzf` installed, but want to opt out of using this feature, set the environment variable `KUBECTX_IGNORE_FZF=1`.

I have the `KUBECTX_IGNORE_FZF` var set and it doesn't seem to be respected. I double checked (`echo $KUBECTX_IGNORE_FZF`) and it is set to 1. I set it in my `.bashrc` file...

**Comment by ahmetb** [comment]
can you run `DEBUG=1  kubectx` and send its output?

**Comment by ahmetb** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubectx.rb
Can you check you’re on 0.6.1 with “brew info kubectx”?

**Comment by karuppiah7890** [comment]
Yup, I am on the latest version, here's the output

```
kubectx: stable 0.6.1, HEAD
Tool that can switch between kubectl contexts easily and create aliases
https://github.com/ahmetb/kubectx
/usr/local/Cellar/kubectx/0.4.0 (11 files, 24.5KB)
  Built from source on 2018-02-27 at 16:45:40
/usr/local/Cellar/kubectx/0.6.1 (12 files, 30.2KB) *
  Built from source on 2018-09-03 at 12:52:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubectx.rb
==> Dependencies
Recommended: kubernetes-cli
==> Options
--with-short-names
	link as "kctx" and "kns" instead
--without-kubernetes-cli
	Build without kubernetes-cli support
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 2,637 (30 days), 9,040 (90 days), 18,743 (365 days)
install_on_request: 2,631 (30 days), 9,001 (90 days), 18,680 (365 days)
build_error: 0 (30 days)
```

**Comment by ahmetb** [comment]
Hmm looks like it's not in the v0.6.1 tag: https://github.com/ahmetb/kubectx/blob/v0.6.1/kubectx#L163

I don't think we've actually tagged this in a release yet. My bad.

**Comment by karuppiah7890** [comment]
Oh, okay. Next release it is then :)

**Comment by maximbaz** [comment]
@ahmetb it would have been a bit more Unix'y if you didn't hardcode `fzf` support (which as you discovered now requires writing even more code to support disabling `fzf` integration), but instead focused on having your scripts do one job well, and then simply documenting in README how to integrate your tool with __any__ existing fuzzy filter tool.

For example, if you didn't have anything about `fzf` in your scripts, a user could have just added this alias to get this feature:

```
alias kc='kubectx "$(kubectx | fzf)"'
```

People who use alternative fuzzy filters (e.g. I use `fzy`) have a very similar setup:

```
alias kc='kubectx "$(kubectx | fzy)"'
```

These aliases work well even today, all I'm saying is that you don't really need to treat `fzf` any differently and writing extra code for it.

**Comment by ahmetb** [comment]
@maximbaz I agree from the perspective of modularity. However, it's nearly impossible to let existing users know about new features, in this case the aliases.

I guess this one just went through, but please subscribe to issues in the repository. I very frequently open proposal issues discussing how to implement things.

**Comment by ahmetb** [comment]
@maximbaz theoretically adding fzf wasn't a breaking change. For users without fzf installed, it's the same. For users with fzf installed, since I regard kubectx as a strictly interactive (non-scriptable) tool, there are no breaking changes.

Similarly SemVer actually lets you keep using 0.x without doing any major bumps on breaking changes. :) So I'm well making use of that at the moment until things stabilize (and it's stabilizing more).

**Comment by maximbaz** [comment]
By breaking change I meant if you ever decide to cleanup the code and remove hardcoded `fzf` support in favor of having a README note that explains how to integrate `kubectx` with any fuzzy filtering — after all, at some point you will get a feature request to support other fuzzy filter tools 🙂 I wrote this because I understood your previous reply as you would be concerned to do such cleanup because you don't have a way to notify users that something has changed.

Anyway, I merely wanted to give you a feedback, the integration with `fzy` works and I'm very happy 😉 Good job on the tool!

**Comment by ahmetb** [comment]
My bad, I assumed fzy was a typo –took me a while to realize it's an existing tool. Yeah I think the naming of the KUBECTX_FZF_* env vars wasn't smart. That said, we can probably address that in a backwards-compatible way if we get requests.

**Comment by francoran** [comment]
> Hmm looks like it's not in the v0.6.1 tag: https://github.com/ahmetb/kubectx/blob/v0.6.1/kubectx#L163
> 
> I don't think we've actually tagged this in a release yet. My bad.

@ahmetb any timeline for this one? :)

**Comment by ahmetb** [comment]
v0.6.2 is out, homebrew formula will be updated periodically by the brew bot.
